plugins:
  - jekyll-relative-links
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

relative_links:
  enabled: true
  collections: true

theme: jekyll-theme-cayman

include:
  - index.md

title: sunarch
description: home page on GitHub
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]

collections:

  c_directors:
    output: true
    sort_by: last_name

  c_series:
    output: true
    sort_by: title
